### ISSUE TITLE
should node_modules be checked in?

### ISSUE THREAD

**Issue by eitansuez** [tetratelabs/istio-cheatsheet#1]
usually with nodejs when you npm install your dependencies get downloaded.  but i see here that node_modules is checked in to the repo.  was this in error?

**Comment by rootsongjc** [comment]
I tried to build a docker image and use GitHub Action to compile a static website, but some of the npm packages were always missing, so I pushed all the npm packages that the project depended on to the repository. Do you have any idea to deploy it to tetratelabs.io? @eitansuez

**Comment by rootsongjc** [comment]
`node_modules` folder removed.
